
import os
import django

# Configurar entorno de Django
# Asegurate de poner el nombre correcto de tu proyecto
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")
django.setup()

# Importar el modelo

artist_not_allowed = {
    "&ME",
    "Aaron Hibell",
    "Adam Port",
    "Adam Ten",
    "Adriatique",
    "Agustin Giri",
    "Ajna (BE)",
    "Alan Dixon",
    "Alex Wann",
    "ALLKNIGHT",
    "Anton Khabbaz",
    "Arabic Piano",
    "Aya Anne",
    "Báez & Saint",
    "Benny Benassi",
    "Black Coffee",
    "Bless You",
    "Bob Sinclar",
    "Carl Bee",
    "Carlo Whale",
    "Crazy Sonic",
    "DAVI",
    "DJ Koze",
    "Einmusik",
    "Ellie Goulding",
    "Empire Of The Sun",
    "Enamour",
    "Everything Is Art",
    "Fancy Inc",
    "Franky Wah",
    "Gespona",
    "Good Guy Mikesh",
    "Guy Gerber",
    "Hero Baldwin",
    "Ink",
    "Interplanetary Criminal",
    "Ivory (IT)",
    "JAiMES",
    "Jain",
    "JEWELS",
    "Jody Wisternoff",
    "Joris Voorn",
    "JUNO (DE)",
    "Kaz James",
    "Keinemusik",
    "Kettama",
    "Kolsch",
    "LE YORA",
    "Luttrell",
    "MAXI MERAKI",
    "Meca",
    "MEUTE",
    "Michael Ekow",
    "Mind Against",
    "Moderat",
    "Molly Moonwater",
    "Monkey Safari",
    "Nandu",
    "Neon Capital",
    "nimino",
    "Nora En Pure",
    "Notre Dame",
    "Nu-La",
    "Osfur",
    "Rampa",
    "Reznik (DE)",
    "Rhye",
    "RÜFÜS DU SOL",
    "Samm (BE)",
    "Sarah De Warren",
    "Simon Doty",
    "Solique",
    "Solee",
    "Solomun",
    "SOMMA",
    "Supermode",
    "The Chainsmokers",
    "The Scripture",
    "The Temper Trap",
    "Tim Engelhardt",
    "Tinlicker",
    "Trikk",
    "Tripolism",
    "UVITA",
    "White Lies",
    "WhoMadeWho",
    "YOTTO",
    "YUMA.",
    "Zerb"
}

print(artist_not_allowed)
