# Generated by Django 5.2 on 2025-04-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('YES', 'Allowed'), ('NO', 'Not Allowed'), ('NEW', 'New')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('YES', 'Allowed'), ('NO', 'Not Allowed'), ('NEW', 'New')], max_length=3)),
                ('songs', models.ManyToManyField(related_name='artist', to='dj.song')),
            ],
        ),
    ]
