# Generated by Django 5.2 on 2025-05-03 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('YES', 'Allowed'), ('BAN', 'Not Allowed'), ('NEW', 'Pending')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('YES', 'Allowed'), ('BAN', 'Not Allowed'), ('NEW', 'Pending')], max_length=3)),
                ('artists', models.ManyToManyField(related_name='songs', to='dj.artist')),
            ],
        ),
    ]
