# Generated by Django 5.2 on 2025-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
