# Generated by Django 5.2 on 2025-04-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(related_name='artists', to='dj.song'),
        ),
    ]
