# Generated by Django 5.2 on 2025-04-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0002_alter_artist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', to='dj.artist'),
        ),
    ]
